trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

resources:
  repositories:
  - repository: templates
    type: github
    name: osisoft/OSI-Samples
    endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: projPath
    value: '/'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.sds_dotnet_rest.json
  - name: analysisProject
    value: SDS_DotNet_REST

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/SdsRestApiCore

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(imageName)'
          workingDirectory: $(Build.SourcesDirectory)$(projPath)/

  - template: '/miscellaneous/build_templates/analysis.yml@templates'
    parameters:
      language: dotnet
